name: Echo Success

on:
  workflow_call:
    inputs:
      message:
        description: "Message to print"
        required: true
        type: string

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "${{ inputs.message }}"
