name: "My first job ever"

on:
  push:
    branches: [ main ]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/echo.yml
    with:
      deploy-env: "production"
    secrets: inherit

  print-output:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    environment: production
    steps:
      - name: Print version
        run: echo "App version is ${{ needs.call-reusable-workflow.outputs.app-version }}"

      - name: Print branch
        run: echo "branch is $GITHUB_REF"
      - name: Print branch again
        run: echo "branch is $GITHUB_REF"
