name: 'Build and deploy'

on:
  workflow_dispatch:
    inputs:
      deploy-env:
        description: 'The environment to deploy to'
        required: false
        type: string
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build

  success:
    needs: build
    uses: ./.github/workflows/echo.yml
    with:
      message: "✅ Build completed successfully in ${{ github.workflow }} workflow!"
